---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by aimozg.
--- DateTime: 17.06.2018 0:07
---

--- Namespaces implementation

_NAMESPACES = {};
function createNamespace(name, parent)
    if parent == '' or parent == nil then
        parent = _ENV
    elseif type(parent) == 'string' then
        parent = _NAMESPACES[parent]
    end
    local e = setmetatable({}, { __index = parent })
    _NAMESPACES[name] = e
    return e
end
function getNamespace(name)
    return _NAMESPACES[name]
end
function removeNamespace(name)
    _NAMESPACES[name] = nil
end
function checkNamespaceMember(ns, member)
    return _NAMESPACES[ns][member] ~= nil
end
function getNamespaceMember(ns, member)
    return _NAMESPACES[ns][member]
end
function setNamespaceMember(ns, member, value)
    _NAMESPACES[ns][member] = value
end
setmetatable(_NAMESPACES, {
    __index = function(table, key)
        return createNamespace(key, _ENV)
    end
})